### ISSUE TITLE
Isabelle/HOL

### ISSUE THREAD

**Issue by fourtytwo** [leoprover/Leo-III#40]
Hi, I was wondering if Leo-III can already be used with Isabelle. If not, is there anyone currently working on an interface?

**Comment by cbenzmueller** [comment]
Hi,

no I don't think that somebody is currently working on an interface. So
there seems room for contributions.

Best,
 C.

--
Priv.-Doz. Dr.-Ing. Christoph Benzmüller
Faculté des Sciences, de la Technologie et de la Communication, Avenue de
l'Université, L-4365 Esch-sur-Alzette, Luxembourg
Further Affiliations:
Freie Universität Berlin, Department of Mathematics and Computer Science
Saarland University, Department of Computer Science
http://christoph-benzmueller.de
c.benzmueller@gmail.com | christoph.benzmueller@uni.lu |
c.benzmueller@fu-berlin.de

**Comment by fourtytwo** [comment]
I see, who was the person responsible for the Leo2 interface for isabelle?

**Comment by cbenzmueller** [comment]
Well, Jasmin Blanchette was involved, I guess, and Nik Sultana.

Best, C.

--
Priv.-Doz. Dr.-Ing. Christoph Benzmüller
Faculté des Sciences, de la Technologie et de la Communication, Avenue de
l'Université, L-4365 Esch-sur-Alzette, Luxembourg
Further Affiliations:
Freie Universität Berlin, Department of Mathematics and Computer Science
Saarland University, Department of Computer Science
http://christoph-benzmueller.de
c.benzmueller@gmail.com | christoph.benzmueller@uni.lu |
c.benzmueller@fu-berlin.de

**Comment by lex-lex** [comment]
Leo-III is now integrated into the current development version of Isabelle (see http://isabelle.in.tum.de/repos/isabelle/rev/41f1f8c4259b). Note that, however, we will need to wait for the next Isabelle release to have this integration delivered with a current Isabelle version.

**Comment by fourtytwo** [comment]
Just as a note. 
Sledgehammer currently does not work with the newest version of Satallax. This is NOT ONLY because the indexing of the steps has changed. However, in the current "development" version of Satallax, the indexing has changed again to behave like the previous versions. Nevertheless it(the development version) still does not work with Sledgehammer.
