### ISSUE TITLE
Splitt README.md

### ISSUE THREAD

**Issue by andreas-roehler** [leoprover/Leo-III#42]
Splitt README.md into README.md, USAGE.md, INSTALL.md

Allow faster orientation and easier edits

**Comment by andreas-roehler** [comment]
Hmm, following the last part WRT to prominent features. Also with splitting the work certainly isn't done, a further cleanup and extending should follow. IMO every section should be complete and kind of hierachical. Giving some details an prominent place without surrounding info doesn't look useful. The precise case was a stumpling about the download advice - which doesn't tell about the directory etc. But understanding is also a personal thing. So lets try your suggestion. We can change it at any time later if important. BTW I'm still struggling with the links. Don't see how to write relative links. only a complete URL works for now.

**Comment by lex-lex** [comment]
> IMO every section should be complete and kind of hierachical.
Yes, of course. That is true.

> Giving some details an prominent place without surrounding info doesn't look useful.
The idea is that only those important information are given on the ovewview page that do not need surrounding information.

But I'll guess we move this discussion to other channels. Thanks for your work!

**Comment by andreas-roehler** [comment]
On 08.01.2018 13:04, Alexander Steen wrote:
>     IMO every section should be complete and kind of hierachical.
>     Yes, of course. That is true.
> 
>     Giving some details an prominent place without surrounding info
>     doesn't look useful.
>     The idea is that only those important information are given on the
>     ovewview page that do not need surrounding information.
> 
> But I'll guess we move this discussion to other channels. Thanks for 
> your work!


My thanks too.

BTW IIRC exists some general leo-dev list. Maybe use this, so others may 
participate?

Cheers,

Andreas
