### ISSUE TITLE
Missing link from FU-page

### ISSUE THREAD

**Issue by andreas-roehler** [leoprover/Leo-III#60]
Starting from 

http://page.mi.fu-berlin.de/lex/leo3/

there was a link to some release here, but no mention like "Developing..." pointing to this repo.
Suggesting a new chapter after "Downloads".

**Comment by lex-lex** [comment]
Good point, I will address this.

**Comment by lex-lex** [comment]
Done :)
There's now a Github-corner-icon at the leo3 page pointing to the repository.
