### ISSUE TITLE
SYN000~1.p causes problems with git on Windows (as a DOS-style 8.3 filename)

### ISSUE THREAD

**Issue by ComFreek** [leoprover/Leo-III#67]
In [src/test/resources/SYN000](https://github.com/leoprover/Leo-III/tree/49d4944d205a36cd2daad6e6143b554ac18534aa/src/test/resources/problems/SYN000) there is a file `SYN000~1.p`.
This causes some annoyances with git on Windows on an NTFS-formatted partition due to historic DOS-style 8.3 filename conventions, see ["Unable to add files with name containing tilde, '~' followed by a number" on StackOverflow](https://stackoverflow.com/a/29300360/603003).

Is there any chance this file could be renamed? :smile:

**Comment by lex-lex** [comment]
Hi there, sorry for the late reply!
I really didn't know this, thanks for pointing it out. It named after the standard TPTP naming conventions, so it's all the more surprising that this didn't bubble up before. I'll rename the file later today!

Best
Alex

**Comment by lex-lex** [comment]
Done in efca73a1f5609c9c3e477f93248c4f441ace4286, should hopefully resolve this issue :-)
