### ISSUE TITLE
Error running Leo-III on SUMO.thf

### ISSUE THREAD

**Issue by apease** [leoprover/Leo-III#71]
I tried running Leo-III on the latest SUMO, using output from Sigma's THF translator (written by Christoph).  I'm getting

apease@apease-ThinkPad-L14-Gen-1:~/workspace/Leo-III/Leo-III-1.6$ bin/leo3 /home/apease/.sigmakee/KBs/SUMO.thf -t 60 -p
% [INFO] 	 Parsing problem /home/apease/.sigmakee/KBs/SUMO.thf ... 
% OUT OF CHEESE ERROR +++ MELON MELON MELON +++ REDO FROM START
% SZS status SyntaxError for /home/apease/.sigmakee/KBs/SUMO.thf : Parse error in file '/home
/apease/.sigmakee/KBs/SUMO.thf' in line 1692:309. Unrecognized thf formula input 'APP'

But there's not string 'APP' in the file.  The context of line 1692 (1690-1694) is

 thf(ax44,axiom,((subclass_THFTYPE_IiioI @ lAquaticMammal_THFTYPE_i @ lMammal_THFTYPE_i))).

 thf(ax45,axiom,((! [PHRASE: $i]: ((instance_THFTYPE_IiioI @ PHRASE @ lPhrase_THFTYPE_i) => (? [PART1: $i,PART2: $i]: ((part_THFTYPE_IiioI @ PART1 @ PHRASE) & (part_THFTYPE_IiioI @ PART2 @ PHRASE) & (instance_THFTYPE_IiioI @ PART1 @ lWord_THFTYPE_i) & (instance_THFTYPE_IiioI @ PART2 @ lWord_THFTYPE_i) & (~ @ (PART1 = PART2)))))))).

%%% notTranslated: (documentation Motion EnglishLanguage "Any &%Process of movement.")
[SUMO.thf.zip](https://github.com/leoprover/Leo-III/files/8794515/SUMO.thf.zip)

I'm enclosing the full file and would be grateful for your help.

**Comment by cbenzmueller** [comment]
Hi Adam,

when you remove the "@" before "(PART1 = PART2)" it works; see below.

Best, C.

thf(ax44,axiom,((subclass_THFTYPE_IiioI @ lAquaticMammal_THFTYPE_i @
lMammal_THFTYPE_i))).

thf(ax45,axiom,((! [PHRASE: $i]: ((instance_THFTYPE_IiioI @ PHRASE @
lPhrase_THFTYPE_i) => (? [PART1: $i,PART2: $i]: ((part_THFTYPE_IiioI @
PART1 @ PHRASE) & (part_THFTYPE_IiioI @ PART2 @ PHRASE) &
(instance_THFTYPE_IiioI @ PART1 @ lWord_THFTYPE_i) &
(instance_THFTYPE_IiioI @ PART2 @ lWord_THFTYPE_i) & (~ (PART1 =
PART2)))))))).

**Comment by lex-lex** [comment]
Alternatively, usage of "connectives as terms", as in negation applied to X, needs to be but in parentheses in THF (this was changed a few years ago, when I recall correctly), e.g., ...

`(~) @ (PART1 = PART2)`

... is valid THF and can be parsed by Leo-III.

As full formula:
```
thf(ax45,axiom,((! [PHRASE: $i]: ((instance_THFTYPE_IiioI @ PHRASE @ lPhrase_THFTYPE_i) => (? [PART1: $i,PART2: $i]: ((part_THFTYPE_IiioI @ PART1 @ PHRASE) & (part_THFTYPE_IiioI @ PART2 @ PHRASE) & (instance_THFTYPE_IiioI @ PART1 @ lWord_THFTYPE_i) & (instance_THFTYPE_IiioI @ PART2 @ lWord_THFTYPE_i) & ((~) @ (PART1 = PART2)))))))).
```

Hope this helps!

Best, Alex

**Comment by apease** [comment]
Many thanks!  I'll see if I can update the translation code
